spring.config.import=optional:file:./application-local.properties
server.port=${PORT:8081}
spring.datasource.url=${ORACLE_URL:jdbc:oracle:thin:@localhost:1521/FREEPDB1}
spring.datasource.username=${ORACLE_USERNAME:SMARTMOVE}
spring.datasource.password=${ORACLE_PASSWORD:}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.maximum-pool-size=5
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017}
spring.data.mongodb.database=${smartmove.mongodb.database:smartmove_db}
smartmove.mongodb.database=${MONGODB_DATABASE:smartmove_db}
spring.servlet.multipart.max-file-size=9MB
spring.servlet.multipart.max-request-size=9MB
spring.jackson.serialization.write-dates-as-timestamps=false
smartmove.security.api-key=${SMARTMOVE_API_KEY:}
